name: CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    env:
      BUILD_CONFIG: Release

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
  
      - name: Get release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Add github packages source
        run: dotnet nuget add source --username Semifinals --password ${{ secrets.GITHUB_TOKEN  }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Semifinals/index.json"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration $BUILD_CONFIG -p:Version=${VERSION} --no-restore

      - name: Run tests
        run: dotnet test /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal

      - name: Package the project
        run: dotnet pack --configuration $BUILD_CONFIG

      - name: Publish to GPR
        run: dotnet nuget push "Apim/bin/${{ env.BUILD_CONFIG }}/Semifinals.Apim.${VERSION}.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
